### PR TITLE
feat/added Tanstack Router and Bootstrap 

### PR DESCRIPTION
**Pull request by mjh316**
- Added tanstack routing and bootstrap
- Added some boilerplate for the website

### CODE REVIEW

**Review by don-mo — COMMENTED** [review]
# Notes!!
#### Src ❗ 
 - Nice use of bootstrap and react.js
 - For Line 26 in index.js, will we need to use a different type of routing when we switch to AWS?
#### Public 🧑‍🦲 
 - how come there is a index.html here and a index.js? Should they be named different things or are they separate web pages lol

**Comment by mjh316** [comment]
> # Notes!!
> #### Src ❗
> * Nice use of bootstrap and react.js
> * For Line 26 in index.js, will we need to use a different type of routing when we switch to AWS?
Attempted to fix our routing to use the Browser History API with a patch in the index.html and 404.html files, the steps I used can be found [here](https://github.com/rafgraph/spa-github-pages). We just need to remove the relevant scripts in the 2 files when we switch to AWS and we should be fine.
> #### Public 🧑‍🦲
> * how come there is a index.html here and a index.js? Should they be named different things or are they separate web pages lol
[Answer](https://stackoverflow.com/questions/63406249/react-entry-point-index-html-vs-index-js-where-is-the-node-code#:~:text=In%20simple%20words%3A%20index.,all%20your%20JS%20codes%20exist.)

**Comment by don-mo** [comment]
> > # Notes!!
> > #### Src ❗
> > 
> > * Nice use of bootstrap and react.js
> > * For Line 26 in index.js, will we need to use a different type of routing when we switch to AWS?
> >   Attempted to fix our routing to use the Browser History API with a patch in the index.html and 404.html files, the steps I used can be found [here](https://github.com/rafgraph/spa-github-pages). We just need to remove the relevant scripts in the 2 files when we switch to AWS and we should be fine.
> > Hey yo Justin to makes sure we are able to switch to aws and be able to show UW students our project with no problems, when you say we just remove the relevant 2 scripts do you mean
```
const memoryHistory = createMemoryHistory({
  initialEntries: ["/"]
});
```
> > 
> > #### Public 🧑‍🦲
> > 
> > * how come there is a index.html here and a index.js? Should they be named different things or are they separate web pages lol
> >   [Answer](https://stackoverflow.com/questions/63406249/react-entry-point-index-html-vs-index-js-where-is-the-node-code#:~:text=In%20simple%20words%3A%20index.,all%20your%20JS%20codes%20exist.)
> > epic

**Comment by mjh316** [comment]
> > > # Notes!!
> > > #### Src ❗
> > > 
> > > * Nice use of bootstrap and react.js
> > > * For Line 26 in index.js, will we need to use a different type of routing when we switch to AWS?
> > >   Attempted to fix our routing to use the Browser History API with a patch in the index.html and 404.html files, the steps I used can be found [here](https://github.com/rafgraph/spa-github-pages). We just need to remove the relevant scripts in the 2 files when we switch to AWS and we should be fine.
> > >   Hey yo Justin to makes sure we are able to switch to aws and be able to show UW students our project with no problems, when you say we just remove the relevant 2 scripts do you mean
> 
> ```
> const memoryHistory = createMemoryHistory({
>   initialEntries: ["/"]
> });
> ```
> 

Oh whoops, I meant the these lines in the `index.html` file.
Screenshot 2024-02-18 at 5 00 47 PM

And these lines in the `404.html` file (or if removing these lines don't work, just remove the `404.html` file entirely.)
Screenshot 2024-02-18 at 5 01 47 PM

It might work on AWS too, but if it doesn't then removing these two chunks of code should do the trick.

**Review by don-mo — APPROVED** [review]
Looks Good!

**Pull request merged**
